#!/usr/bin/expect -f

log_user 0
exp_internal 0

# initialization
set old_pass [lindex $argv 0]
set new_pass [lindex $argv 1]

spawn passwd

expect "(current) UNIX password: "
send "$old_pass\r"
expect {
	"New password:" {
		send "$new_pass\r"
	}
	"passwd: Authentication token manipulation error" {
		send_user "Wrong password\n"
		exit 1
	}
}
expect {
	"Retype new password:" {
		send "$new_pass\r"
	}
	"BAD PASSWORD:" {
		send_user "Bad password\n"
		exit 2
	}
	default {
		send_user "Unknown error\n"
		exit 4
	}
}
expect {
	"passwd: password updated successfully" {
		exit 0
	}
	"Password has been already used. Choose another." {
		send_user "Match password history\n"
		exit 3
	}
}
